# @server = https://pif-api.herokuapp.com
@server = http://localhost:3030
@api = {{server}}/v1/en

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoS2V5IjoiYTExYTI0ZTktMjVlZi00NDRkLWFjNzItNzExNWFiYTUxZGU1IiwiZGV2aWNlSWQiOiI0YTdiZDM0MTk4ZWJlMmVmMjgzNjAzYzU3ZWQ2MzZkMzI0Y2FmOTQ3MzhhNGFlYzFjNTFhMGQ0N2Y0NTQyOTJlIiwidXNlclR5cGUiOiJwbGF0Zm9ybS1hZG1pbiIsInJvbGUiOiJzdXBlci1hZG1pbiIsInNlc3Npb25JZCI6IjJiM2IwZjRjLWM2MGQtNDEwOS1hMzEyLTViNDk0ZTA0YmQ5OCIsInJlZiI6IjY0OGYwNWEyMjAzNjBlODU4YTk1ZjdhYyIsImlhdCI6MTY4NzExODU0MywiZXhwIjoxNjg3MjkxMzQzLCJpc3MiOiJQSUYtZGV2In0.dFHuH8FWWB5BSQQvgZZpFkOtPK9crnjUyFjWCpkqjy0

GET {{server}}

### API
GET {{api}}

### dashboard login
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "piftech@pif-app.com",
  "password": "Password_1"
}

# "email": "piftech@pif-app.com",

### my profile
GET {{api}}/users/my-profile
Authorization: Bearer {{token}}

### invite users
POST {{api}}/users/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "afeez@pif-app.com",
  "userType": "platform-admin",
  "role": "country-admin",
  "marketplaces": ["ghana"]
}

### invite users
GET {{api}}/users/verify-invite/a0261fb7-a6a5-4c50-b7e1-7d64dd57d72f

### finalize users invite
POST {{api}}/users/accept-invite
Content-Type: application/json

{
 "name": "Jalasem Ajala",
 "email": "kgasta@gmail.com",
 "code": "a0261fb7-a6a5-4c50-b7e1-7d64dd57d72f",
 "phonePrefix": "234",
"phone": "8168861541",
"password": "Password_1"
}

### dashboard - forgot password
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
  "email":"Jimohafeez738@gmail.com"
}

### dashboard - reset password
POST {{api}}/auth/reset-password
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8103498784",
  "otpCode": "99497",
  "password": "00000"
}

### finalize users invite
POST {{api}}/users/accept-invite
Content-Type: application/json

{
 "name": "Abdul-Afeez",
 "email": "jimohafeez738@gmail.com",
 "code": "22074183-67ca-4b9a-898e-f3d70a3814db",
 "phonePrefix": "234",
"phone": "8103498784",
"password": "Aweda"
}

### dashboard - forgot password
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
  "email":"Jimohafeez738@gmail.com"
}

### dashboard - reset password
POST {{api}}/auth/reset-password
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8103498784",
  "otpCode": "99497",
  "password": "00000"
}

### dashboard - forgot pin
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
  "email":"jimohafeez738@gmail.com"
}

### dashboard - reset password
POST {{api}}/auth/reset-password
Content-Type: application/json

{
  "email": "jimohafeez738@gmail.com",
  "otpCode": "24691",
  "password": "0000"
}

### mobile signup
POST {{api}}/auth/m-signup
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8103498784",
  "marketplace": "Nigeria"
}

### mobile - verify otp
POST {{api}}/auth/verify-otp
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8103498784",
  "code": "55677",
  "purpose": "signup"
}

### mobile resend otp
POST {{api}}/auth/resend-otp
Content-Type: application/json

{
 "phonePrefix": "234",
  "phone": "8103498784",
  "purpose": "signup"
}


### mobile finalize signup
POST {{api}}/auth/finalize-m-signup
Content-Type: application/json

{
 "name": "Aweds wedi",
 "dob": "1990-02-20",
 "phonePrefix": "234",
 "phone": "8103498784",
 "pifId":"wedi",
 "zipCode":"12345",
 "otpCode":"55677"
}

### mobile set pin
POST {{api}}/auth/set-pin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pin": "1234"
}


### mobile login
POST {{api}}/auth/m-login
Content-Type: application/json

{
 "phonePrefix": "234",
 "phone": "8103498784",
 "pin": "1111"
}

### mobile - forgot pin
POST {{api}}/auth/forgot-pin
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8103498784"
}

### mobile - reset pin
POST {{api}}/auth/reset-pin
Content-Type: application/json

{
  "otpCode": "24691",
  "pin": "0000"
}

### mobile - change pin
POST {{api}}/auth/change-pin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPin": "1234",
  "newPin": "1111"
}

###

GET {{api}}/cms/faq
Authorization: Bearer {{token}}

###

POST {{api}}/cms/faq
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "question": "What is Pifing?",
  "answer": "It means sending a gift to your loved ones and friends",
  "isDraft": false
}

###

GET {{api}}/cms/faq/647f684100839cfd80eec4f8
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "question": "What is Pifing?",
  "answer": "It means sending a gift to your loved one and friends",
  "isDraft": false
}

### get platform data
GET {{api}}/platform

### refresh db
GET {{api}}/platform/refresh

### add partner
POST {{api}}/partners
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Gift Enterprise",
    "email": "giftenterprise@mail.com",
    "phone": "",
    "phonePrefix": "",
    "headquarterAddress": "7 gwagwalada street, fct.",
    "headquarterCity": "Abuja",
    "headquarterCountry": "Nigeria",
    "headquarterZipCode": "242201",
    "marketplaces": ["denmark"],
    "accountName": "Gift Enterprise",
    "accountNumber": "0123456789",
    "bankCountry": "Nigeria",
    "bankName": "first-bank",
    "currency": "naira",
    "redeemType": "mobile-redemption",
    "status": "inactive",
    "isPeriodically": true,
    "periodType": "weekly"
  }

  ###

    # "isAmountThreshold": true,
    # "amountThreshold": "20"
    # "pifProportion": "",
    # "startProportion": "",
    # "transactionAmount": "",
    # "transactionMaximumAmount": "",
    # "vat": "",
    # "website": ""
    # "enablePushNotification": "",
    # "enableRewardSystem": "",
    # "enableTransactionFeeManualSettings": "",
    # "fax": "",
    # "finishProportion": "",
    # "fixedFee": "",
    # "isCharity": "",

    ###

### get partner
GET {{api}}/partners

### get partner by market
GET {{api}}/partners/nigeria


### update partner
PATCH {{api}}/partners/1001
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "currency": "naira",
    "phonePrefix": "234",
    "phone": "8123456789",
    "headquarterAddress": "7 gwagwalada street, fct.",
    "headquarterCity": "Abuja",
    "headquarterCountry": "Nigeria",
    "headquarterZipCode": "242201",
    "marketplaces": ["nigeria"],
    "accountName": "Gift Enterprise",
    "accountNumber": "0123456789",
    "bankCountry": "Nigeria",
    "bankName": "first-bank",
    "redeemType": "mobile-redemption",
    "status": "inactive",
    "isAmountThreshold": true,
    "amountThreshold": "20",
    "isPeriodically": true,
    "periodType": "daily"
  }


  ###

  