# @server = https://pif-api.herokuapp.com
@server = http://localhost:3000
@api = {{server}}/v1/en

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoS2V5IjoiOTY5YTIyOGQtN2NlYi00Y2NmLTlhZWQtZTI0MDQxODViOGYyIiwiZGV2aWNlSWQiOiI0YTdiZDM0MTk4ZWJlMmVmMjgzNjAzYzU3ZWQ2MzZkMzI0Y2FmOTQ3MzhhNGFlYzFjNTFhMGQ0N2Y0NTQyOTJlIiwidXNlclR5cGUiOiJwbGF0Zm9ybS1hZG1pbiIsInJvbGUiOiJhZG1pbiIsInNlc3Npb25JZCI6IjdmNjdhZGYwLTcyMjMtNDk4ZS04YzNhLWNhNGNjOGQxNjllYSIsInJlZiI6IjY0ZGI1NGM2YmIzMmY2MmMxYjA0ZmQzOCIsImlhdCI6MTY5MjM1NDg1MiwiZXhwIjoxNjkyNTI3NjUyLCJpc3MiOiJQSUYtZGV2In0.O-mQtq9ERnTU1MPSXfsCe4XZuhxULDKBtUTw-4QVcMI
# @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoS2V5IjoiMDRjMDA2Y2YtMTk4ZC00N2NmLTg4ZDktYzVmMTlhYWRkNjM2IiwiZGV2aWNlSWQiOiI0YTdiZDM0MTk4ZWJlMmVmMjgzNjAzYzU3ZWQ2MzZkMzI0Y2FmOTQ3MzhhNGFlYzFjNTFhMGQ0N2Y0NTQyOTJlIiwidXNlclR5cGUiOiJjdXN0b21lciIsInNlc3Npb25JZCI6ImJmMmVlMTg2LTRlZTYtNDBiMy1hZWIwLWE4NzUyMDg0ZWUyNyIsInJlZiI6IjY0Y2FiNThhYTFlMGExMmM5OGY5ZGNkMiIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTY5MjE5NzA4OSwiZXhwIjoxNjkyMzY5ODg5LCJpc3MiOiJQSUYtZGV2In0.KGBmIcyzZ9fisHwOAl9pChGQcoXxpyxa3v5ECWCvy1k

GET {{server}}

### API
GET {{api}}

### dashboard login
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "oseimensahisaiah@gmail.com",
  "password": "BIRAPOMSosei1!"
}

# "email": "piftech@pif-app.com",

### my profile
GET {{api}}/users/my-profile
Authorization: Bearer {{token}}

### update my profile
PATCH {{api}}/users/my-profile
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "Abdulsamii Ajala",
  "phonePrefix": "234",
  "phone": "8168861541",
  "sex": "male",
  "occupation": "software engineer",
  "relationship": "married",
  "dob": "1992-01-08",
  "interests": ["sleeping", "coding"],
  "city": "Selangor",
  "country": "Malaysia",
  "zipCode": "12345",
  "street": "7 gwagwalada street, fct.",
  "social": [{
    "platformName": "facebook",
    "socialUserId": "jalasem"
  }],
  "avatar": "https://pif-space.nyc3.cdn.digitaloceanspaces.com/user-avatars/fake-user-id/0be42d11-f877-42cc-83ae-516dec4087f3.jpeg"
}

### Get users
GET {{api}}/users?search_query=hem
Authorization: Bearer {{token}}

### Get user
GET {{api}}/users/6488460f732eaea68fd743f7
Authorization: Bearer {{token}}
### Get users
GET {{api}}/users
Authorization: Bearer {{token}}

### invite users
POST {{api}}/users/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "afeez@pif-app.com",
  "userType": "platform-admin",
  "role": "admin"
}

### invite users
GET {{api}}/users/verify-invite/a0261fb7-a6a5-4c50-b7e1-7d64dd57d72f

### finalize users invite
POST {{api}}/users/accept-invite
Content-Type: application/json

{
 "name": "Jalasem Ajala",
 "email": "kgasta@gmail.com",
 "code": "a0261fb7-a6a5-4c50-b7e1-7d64dd57d72f",
 "phonePrefix": "234",
"phone": "8168861541",
"password": "Password_1"
}

### dashboard - forgot password
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
  "email":"Jimohafeez738@gmail.com"
}

### dashboard - reset password
POST {{api}}/auth/reset-password
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8103498784",
  "otpCode": "99497",
  "password": "00000"
}

### finalize users invite
POST {{api}}/users/accept-invite
Content-Type: application/json

{
 "name": "Abdul-Afeez",
 "email": "jimohafeez738@gmail.com",
 "code": "22074183-67ca-4b9a-898e-f3d70a3814db",
 "phonePrefix": "234",
"phone": "8103498784",
"password": "Aweda"
}

### dashboard - forgot password
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
  "email":"Jimohafeez738@gmail.com"
}

### dashboard - reset password
POST {{api}}/auth/reset-password
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8103498784",
  "otpCode": "99497",
  "password": "00000"
}

### dashboard - forgot pin
POST {{api}}/auth/forgot-password
Content-Type: application/json

{
  "email":"jimohafeez738@gmail.com"
}

### dashboard - reset password
POST {{api}}/auth/reset-password
Content-Type: application/json

{
  "email": "jimohafeez738@gmail.com",
  "otpCode": "24691",
  "password": "0000"
}

### mobile signup
POST {{api}}/auth/m-signup
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8063107175",
  "marketplace": "ng"
}

### mobile - verify otp
POST {{api}}/auth/verify-otp
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "9093827376",
  "code": "90981",
  "purpose": "confirm-account",
  "email": "jimohafeez738@gmail.com"
}

### mobile resend otp
POST {{api}}/auth/resend-otp
Content-Type: application/json

{
 "phonePrefix": "234",
  "phone": "9093827376",
  "purpose": "confirm-account"
}


### mobile finalize signup (if user signup with phone number
POST {{api}}/auth/finalize-m-signup
Content-Type: application/json

{
 "name": "Ishola Jamiu",
 "dob": "1990-02-20",
 "pifId":"highshow",
 "zipCode":"12345",
 "email": "isholajamiusolihu@gmail.com",
 "referenceCode": "8564dc10c51c112b953fad7fa372676"
}
### mobile finalize signup (if user signup with phone and Google or has ever received a gift before joinning the platform)
POST {{api}}/auth/finalize-m-signup
Content-Type: application/json

{
 "name": "Lekan Ajala",
 "dob": "1990-02-20",
 "pifId":"semite",
 "zipCode":"12345",
 "phonePrefix": "234",
 "phone": "8168861541",
 "otpCode":"38926",
 "email": "jalasem@abdulsamii.com",
}

### mobile set pin
POST {{api}}/auth/set-pin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "pin": "1234"
}


### mobile login
POST {{api}}/auth/m-login
Content-Type: application/json

{
 "phonePrefix": "234",
 "phone": "8168861541",
 "pin": "1234"
}

### mobile - forgot pin
POST {{api}}/auth/forgot-pin
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8063107175"
}

### mobile - reset pin
POST {{api}}/auth/reset-pin
Content-Type: application/json

{
  "otpCode": "63025",
  "pin": "1234",
  "phonePrefix": "234",
  "phone": "8168861541",
  "email": "jalasem@abdulsamii.com"
}

### mobile - change pin
POST {{api}}/auth/change-pin
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "oldPin": "1234",
  "newPin": "1111"
}

### change marketplace
PUT {{api}}/users/my-marketplace/ng
Authorization: Bearer {{token}}

###

GET {{api}}/cms/faq
Authorization: Bearer {{token}}

###

POST {{api}}/cms/faq
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "question": "What is Pifing?",
  "answer": "It means sending a gift to your loved ones and friends",
  "isDraft": false
}

###

GET {{api}}/cms/faq/647f684100839cfd80eec4f8
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "question": "What is Pifing?",
  "answer": "It means sending a gift to your loved one and friends",
  "isDraft": false
}

### get platform data
GET {{api}}/platform

## refresh db // uncomment to refresh db
# GET {{api}}/platform/refresh

### add partner
POST {{api}}/partners
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Gift Enterprise",
  "email": "giftenterprise@mail.com",
  "phone": "",
  "phonePrefix": "",
  "headquarterAddress": "7 gwagwalada street, fct.",
  "headquarterCity": "Abuja",
  "headquarterCountry": "Nigeria",
  "headquarterZipCode": "242201",
  "marketplaces": ["ng"],
  "accountName": "Gift Enterprise",
  "accountNumber": "0123456789",
  "bankCountry": "Nigeria",
  "bankName": "first-bank",
  "currency": "naira",
  "redeemType": "mobile-redemption",
  "status": "inactive",
  "isPeriodically": true,
  "periodType": "weekly"
}

### get partner
GET {{api}}/partners
Authorization: Bearer {{token}}

### update partner
PATCH {{api}}/partners/1002
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "currency": "naira",
  "phonePrefix": "234",
  "phone": "8123456789",
  "headquarterAddress": "7 gwagwalada street, fct.",
  "headquarterCity": "Abuja",
  "headquarterCountry": "Nigeria",
  "headquarterZipCode": "242201",
  "marketplaces": ["nigeria"],
  "accountName": "Gift Enterprise",
  "accountNumber": "0123456789",
  "bankCountry": "Nigeria",
  "bankName": "first-bank",
  "redeemType": "mobile-redemption",
  "status": "inactive",
  "isAmountThreshold": true,
  "amountThreshold": "20",
  "isPeriodically": true,
  "periodType": "daily"
}


### invite partner
POST {{api}}/partners/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "adminEmail": "afeez@pif-app.com",
  "adminName": "Afeez",
  "userType": "partner-admin",
  "role": "partner-admin",
  "partnerId": "1002"
}

### get folder

GET {{api}}/drive/fullpath
Authorization: Bearer {{token}}

###
GET {{api}}/categories/internal
Authorization: Bearer {{token}}

###
GET {{api}}/categories?marketplace=ng
Authorization: Bearer {{token}}

### add category
POST {{api}}/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name":
      {
        "en" : "hello"
      },
      "isEnabled": true,
      "marketplaces": ["ng"]
}

### GET products
GET {{api}}/products/64ca1c27796a7f6389b61942
Authorization: Bearer {{token}}

### add product split prices
PATCH {{api}}/products/64ca1c27796a7f6389b61942
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "canBeSent":"immediately"
}

### Add products
POST {{api}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": {
    "en": "Book of fashion",
    "fr": "Livre de mode",
    "da": "Bog om mode"
  },
  "description": {
    "en": "A book that teaches you how to dress well",
    "fr": "Un livre qui vous apprend à bien vous habiller",
    "da": "En bog, der lærer dig at klæde dig godt"
  },
  "partnerId": "64ba4c0b747b9058134a4020",
  "categories": ["64c7d903597cad7ddb548079", "64c7d903597cad7ddb54807c"],
  "marketplace": "dk",
  "price": 3000,
  "productType": "regular-product",
  "quantity": 100,
  "redemptionValidityType": "period",
  "redemptionValidityPeriodType": "weeks",
  "redemptionValidityValue": "2"
}


### Get products by marketplace, category and partner (no need for auth)
GET {{api}}/products/marketplace/dk/category/64a9a75a02ed5ef9311de15a/partner/64b019d002ed5ef93120530c

### Get partners by categories and marketplace
GET {{api}}/partners/marketplace/dk/category/64a9a75a02ed5ef9311de15a

### Get categories
GET {{api}}/categories?marketplaces=ng
Authorization: Bearer {{token}}

### initiate transaction
POST {{api}}/tx/initiate
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "idempotencyKey": "96ec6f0a-b93f-4e17-b78e-1fd9cf604779",
  "items": [
    {
      "productId": "64be36532976f1a339ed7b4d",
      "quantity": 1
    }
  ],
  "recipientPhonePrefix": "234",
  "recipientPhoneNumber": "8063107175",
  "message": "Just a gift",
  "toBeDeliveredAt": "2023-08-24T13:13:04.247Z",
  "driver": "paystack"
}

### get transaction
GET {{api}}/tx/payment-callback/stripe?reference=pi_3NbDggKdtPrufmFP0L5TWMSB_secret_EtaaQDv3oH1slsqFLk0eMjI98
### payment webhook
GET {{api}}/tx/payment-webhook/paystack

### get purchases
GET {{api}}/purchases?product_id=64b522bfc5cc776a57c2f12b
Authorization: Bearer {{token}}
### get purchases
GET {{api}}/purchases?duration=today
Authorization: Bearer {{token}}

### get purchases
GET {{api}}/purchases/64ca1ce5796a7f6389b619a6
Authorization: Bearer {{token}}

# pi_3NbCMeKdtPrufmFP1fEzL9kS_secret_iUD3cQQ3KFcSWzYcYiK8P8qdi
### get revenue
GET {{api}}/revenue/64ca1ce5796a7f6389b619b1
Authorization: Bearer {{token}}

### get settlements
GET {{api}}/settlements?currency=NGN&search_query=64da4a1e23eb1ad6632f74b7
Authorization: Bearer {{token}}

### my sent PIFs
GET {{api}}/sent-pifs
Authorization: Bearer {{token}}

### get my received PIFs
GET {{api}}/received-pifs
Authorization: Bearer {{token}}

### unwrap PIF
PATCH {{api}}/received-pifs/64cabb481886e1c8b409e044/unwrap
Authorization: Bearer {{token}}

###
GET {{api}}/categories/marketplaces/ng

### 
GET {{api}}/partners/marketplaces/dk/categories/64c7d903597cad7ddb548079

###
GET {{api}}/products/marketplace/ng/category/64b66f6d3ff189c2c9a33795/partner/64b1101d3e5b42da83eb9425

### get purchases
GET {{api}}/purchases/64d1834e314d3fa95830a440
Authorization: Bearer {{token}}

### 
GET {{api}}/bank-info/list-banks?driver=paystack&marketplace=ng
Authorization: Bearer {{token}}
###
POST {{api}}/bank-info/resolve-account-number?partner_id=64dbf05ceb8530601705fde2
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "driver": "paystack",
  "marketplace": "ng",
  "accountNumber": "0123342055",
  "bankCode": "058"
}

###
POST {{api}}/bank-info/add-account-number?partner_id=64b1101d3e5b42da83eb9425
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "driver": "paystack",
  "marketplace": "ng",
  "accountNumber": "0123342055",
  "bankCode": "058"
}
###
GET {{api}}/bank-info?partner_id=64b1101d3e5b42da83eb9425
Authorization: Bearer {{token}}
###
POST {{api}}/bank-info/64d60c2bf5a6730f2b558133/enable?partner_id=64b1101d3e5b42da83eb9425
Authorization: Bearer {{token}}
###
GET {{api}}/platform/gen-key-hash
Authorization: Bearer {{token}}

###
GET https://pif-api.herokuapp.com/v1/en/purchases?page=1&per_page=20&user_id=64b52205c5cc776a57c2efbb
Authorization: Bearer {{token}}


### Get dashboard Data
GET {{api}}/platform/dashboard-data?duration=this_week
Authorization: Bearer {{token}}

### get wallets
GET {{api}}/wallets?marketplace=ng&has_money=true
Authorization: Bearer {{token}}
### payouts
GET {{api}}/payouts?payout_id=64dcd4b12aa801864012f568
Authorization: Bearer {{token}}
###
GET {{api}}/platform/dashboard-data
Authorization: Bearer {{token}}
### 
GET {{api}}/purchases?page=1&per_page=20&user_id=64cab58aa1e0a12c98f9dcd2
Authorization: Bearer {{token}}