@server = http://localhost:3030
@api = {{server}}/v1/en
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoS2V5IjoiZTZmM2ViZWEtOGEwNi00MGMxLWJlNWEtZjc0NWQwMTM4NTA0IiwiZGV2aWNlSWQiOiI0YTdiZDM0MTk4ZWJlMmVmMjgzNjAzYzU3ZWQ2MzZkMzI0Y2FmOTQ3MzhhNGFlYzFjNTFhMGQ0N2Y0NTQyOTJlIiwidXNlclR5cGUiOiJhZG1pbiIsInNlc3Npb25JZCI6ImJmOWQxYTZlLWM5M2MtNDljZS1hOTJjLWM5YWQwNjBhZTEwMyIsInJlZiI6IjY0NTNlNzI5YmZiN2ExNDdmY2E2ODU5OSIsImlhdCI6MTY4NTM3OTQyMSwiZXhwIjoxNjg1NTUyMjIxLCJpc3MiOiJQSUYtZGV2In0.XswhL12SKooDCRcogge1lWwtP-CdAQyONz32TyzGOKM

GET {{server}}

### API
GET {{api}}

### dashboard login
POST {{api}}/auth/login
Content-Type: application/json

{
  "email": "piftech@pif-app.com",
  "password": "Password_1"
}

### my profile
GET {{api}}/user/my-profile
Authorization: Bearer {{token}}

### invite user
POST {{api}}/user/invite
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "email": "kgasta@gmail.com",
  "role": "admin"
}

### invite user
GET {{api}}/user/invite/893675a2-0e60-47f2-9e71-274d31270096

### mobile signup
POST {{api}}/auth/m-signup
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "8168861541",
  "marketplace": "Nigeria"
}

### mobile - verify otp
POST {{api}}/auth/verify-m-signup
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "7032434744",
  "code": "86173"
}

### mobile resend otp
POST {{api}}/auth/resend-otp
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "7032434744",
  "purpose": "signup"
}


### mobile finalize signup
POST {{api}}/auth/finalize-m-signup
Content-Type: application/json

{
 "name": "Muzammil Opayemi",
 "dob": "1990-02-20",
 "phonePrefix": "234",
 "phone": "7032434744",
 "pifId":"semo",
 "zipCode":"12345",
 "otpCode":"86173"
}

### mobile set pin
POST {{api}}/auth/m-pin
Content-Type: application/json

{
  "pin": "1234"
}


### mobile login
POST {{api}}/auth/m-login
Content-Type: application/json

{
  "phonePrefix": "234",
  "phone": "7065516083",
  "pin": "1234"
}